---
engines:
  fixme:
    enabled: false
ratings:
  paths:
  - "src/js/**/**.js"
  - "src/js/**/**.jsx"
  enabled: false
exclude_paths:
- node_modules/
- tests/
- public/
- coverage/
- cache/
- gulpfile.babel.js